config/routes.rb
Rails.application.routes.draw do
  resources :candidates
  resources :parties

  root 'welcome#index'

end

app/models/candidate.rb
class Candidate < ActiveRecord::Base
  belongs_to :party
end

app/models/party.rb
class Party < ActiveRecord::Base
  has_many :candidates
end

app/models/service.rb
class Service
	def self.update
		# login to betfair
		require 'betfair'
		# # create a client with app code
		client = Betfair::Client.new("X-Application" => ENV["CLIENTCODE"])
		# # let's log in.
		client.interactive_login(ENV["USERNAME"], ENV["PASSWORD"])

		# get book for party market
		party_book = client.list_market_book("marketIds": ["1.116006120"])

		# get runners form party_book
		partyrunners = party_book[0]["runners"]

		# Democratic Nominee
		dem_book = client.list_market_book("marketIds": ["1.107664930"])

		# Republican Nominee
		rep_book = client.list_market_book("marketIds": ["1.107664938"])


		# add dem and rep books to get a big list of all primary odds
		big_book = dem_book[0]["runners"] + rep_book[0]["runners"]

		# get market book for presidentual election
		pres_book = client.list_market_book("marketIds": ["1.107373419"])

		# get list of runners from pres_book
		pres_runners = pres_book[0]["runners"]

		# get partys from db, find in party runners by selectionid, update odds and save to db
		Party.all.each do |party|
			partycode = party.betfaircode
			selection = partyrunners.select {|selection| selection["selectionId"] == partycode.to_i }
			party.odds = selection[0]["lastPriceTraded"]
			party.save

		end

		# get candidates from db, find in pbig_book for primary odds and pre_runners for presidency odds, update odds and save to db
		Candidate.all.each do |candidate|
			candicode = candidate.betfaircode

			selection = big_book.select {|selection| selection["selectionId"] == candicode.to_i }
			candidate.primaryodds = selection[0]["lastPriceTraded"]

			selection = pres_runners.select {|selection| selection["selectionId"] == candicode.to_i }
			candidate.presidencyodds = selection[0]["lastPriceTraded"]

			candidate.save
		end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController
  before_action :set_candidate, only: [:show, :edit, :update, :destroy]

  # GET /candidates
  # GET /candidates.json
  def index
    @candidates = Candidate.all
  end

  # GET /candidates/1
  # GET /candidates/1.json
  def show
  end

  # GET /candidates/new
  def new
    @candidate = Candidate.new
  end

  # GET /candidates/1/edit
  def edit
  end

  # POST /candidates
  # POST /candidates.json
  def create
    @candidate = Candidate.new(candidate_params)

    respond_to do |format|
      if @candidate.save
        format.html { redirect_to @candidate, notice: 'Candidate was successfully created.' }
        format.json { render :show, status: :created, location: @candidate }
      else
        format.html { render :new }
        format.json { render json: @candidate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /candidates/1
  # PATCH/PUT /candidates/1.json
  def update
    respond_to do |format|
      if @candidate.update(candidate_params)
        format.html { redirect_to @candidate, notice: 'Candidate was successfully updated.' }
        format.json { render :show, status: :ok, location: @candidate }
      else
        format.html { render :edit }
        format.json { render json: @candidate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /candidates/1
  # DELETE /candidates/1.json
  def destroy
    @candidate.destroy
    respond_to do |format|
      format.html { redirect_to candidates_url, notice: 'Candidate was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_candidate
      @candidate = Candidate.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def candidate_params
      params.require(:candidate).permit(:name, :party_id, :betfaircode, :primaryodds, :presidencyodds)
    end
end

app/controllers/parties_controller.rb
class PartiesController < ApplicationController
  before_action :set_party, only: [:show, :edit, :update, :destroy]

  # GET /parties
  # GET /parties.json
  def index
    @parties = Party.all
  end

  # GET /parties/1
  # GET /parties/1.json
  def show
  end

  # GET /parties/new
  def new
    @party = Party.new
  end

  # GET /parties/1/edit
  def edit
  end

  # POST /parties
  # POST /parties.json
  def create
    @party = Party.new(party_params)

    respond_to do |format|
      if @party.save
        format.html { redirect_to @party, notice: 'Party was successfully created.' }
        format.json { render :show, status: :created, location: @party }
      else
        format.html { render :new }
        format.json { render json: @party.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /parties/1
  # PATCH/PUT /parties/1.json
  def update
    respond_to do |format|
      if @party.update(party_params)
        format.html { redirect_to @party, notice: 'Party was successfully updated.' }
        format.json { render :show, status: :ok, location: @party }
      else
        format.html { render :edit }
        format.json { render json: @party.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /parties/1
  # DELETE /parties/1.json
  def destroy
    @party.destroy
    respond_to do |format|
      format.html { redirect_to parties_url, notice: 'Party was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_party
      @party = Party.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def party_params
      params.require(:party).permit(:name, :betfaircode, :odds)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/candidates_helper.rb
module CandidatesHelper
end

app/helpers/parties_helper.rb
module PartiesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/candidates/_form.html.erb
<%= form_for(@candidate) do |f| %>
  <% if @candidate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@candidate.errors.count, "error") %> prohibited this candidate from being saved:</h2>

      <ul>
      <% @candidate.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :party_id %><br>
    <%= f.text_field :party_id %>
  </div>
  <div class="field">
    <%= f.label :betfaircode %><br>
    <%= f.text_field :betfaircode %>
  </div>
  <div class="field">
    <%= f.label :primaryodds %><br>
    <%= f.text_field :primaryodds %>
  </div>
  <div class="field">
    <%= f.label :presidencyodds %><br>
    <%= f.text_field :presidencyodds %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/candidates/edit.html.erb
<h1>Editing Candidate</h1>

<%= render 'form' %>

<%= link_to 'Show', @candidate %> |
<%= link_to 'Back', candidates_path %>

app/views/candidates/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Candidates</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Party</th>
      <th>Betfaircode</th>
      <th>Primaryodds</th>
      <th>Presidencyodds</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @candidates.each do |candidate| %>
      <tr>
        <td><%= candidate.name %></td>
        <td><%= candidate.party %></td>
        <td><%= candidate.betfaircode %></td>
        <td><%= candidate.primaryodds %></td>
        <td><%= candidate.presidencyodds %></td>
        <td><%= link_to 'Show', candidate %></td>
        <td><%= link_to 'Edit', edit_candidate_path(candidate) %></td>
        <td><%= link_to 'Destroy', candidate, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Candidate', new_candidate_path %>

<div class="mygraph">hello</div>

<script>

  // var margin = {top: 20, right: 20, bottom: 30, left: 40},
  //     width = 960 - margin.left - margin.right,
  //     height = 500 - margin.top - margin.bottom;

  // var x = d3.scale.ordinal()
  //     .rangeRoundBands([0, width], .1);

  // var y = d3.scale.linear()
  //     .range([height, 0]);

  // var xAxis = d3.svg.axis()
  //     .scale(x)
  //     .orient("bottom");

  // var yAxis = d3.svg.axis()
  //     .scale(y)
  //     .orient("left")
  //     .ticks(10, "%");

   var svg = d3.select("body").append("svg")
  //     .attr("width", width + margin.left + margin.right)
  //     .attr("height", height + margin.top + margin.bottom)
  //   .append("g")
  //     .attr("transform", "translate(" + margin.left + "," + margin.top + ")");

  // var url = '/courses/1';
// d3.json( url, function( error, data ) {
//     console.log( data );
//     // do all actions required now that the data is retrieved
// } );

  // d3.json("/candidates.json", type, function(error, data) {


  //   if (error) throw error;

  //   x.domain(data.map(function(d) { return d.letter; }));
  //   y.domain([0, d3.max(data, function(d) { return d.frequency; })]);

  //   svg.append("g")
  //       .attr("class", "x axis")
  //       .attr("transform", "translate(0," + height + ")")
  //       .call(xAxis);

  //   svg.append("g")
  //       .attr("class", "y axis")
  //       .call(yAxis)
  //     .append("text")
  //       .attr("transform", "rotate(-90)")
  //       .attr("y", 6)
  //       .attr("dy", ".71em")
  //       .style("text-anchor", "end")
  //       .text("Frequency");

  //   svg.selectAll(".bar")
  //       .data(data)
  //     .enter().append("rect")
  //       .attr("class", "bar")
  //       .attr("x", function(d) { return x(d.letter); })
  //       .attr("width", x.rangeBand())
  //       .attr("y", function(d) { return y(d.frequency); })
  //       .attr("height", function(d) { return height - y(d.frequency); });
  // });

  // function type(d) {
  //   d.frequency = +d.frequency;
  //   return d;
  // }

</script>

app/views/candidates/new.html.erb
<h1>New Candidate</h1>

<%= render 'form' %>

<%= link_to 'Back', candidates_path %>

app/views/candidates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @candidate.name %>
</p>

<p>
  <strong>Party:</strong>
  <%= @candidate.party %>
</p>

<p>
  <strong>Betfaircode:</strong>
  <%= @candidate.betfaircode %>
</p>

<p>
  <strong>Primaryodds:</strong>
  <%= @candidate.primaryodds %>
</p>

<p>
  <strong>Presidencyodds:</strong>
  <%= @candidate.presidencyodds %>
</p>

<%= link_to 'Edit', edit_candidate_path(@candidate) %> |
<%= link_to 'Back', candidates_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Election Tipping</title>

<link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>

<link href='https://fonts.googleapis.com/css?family=Bitter' rel='stylesheet' type='text/css'>

<%= stylesheet_link_tag    'application', media: 'all' %>



 
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>
 <%= javascript_include_tag 'application' %>

</body>
</html>

app/views/parties/_form.html.erb
<%= form_for(@party) do |f| %>
  <% if @party.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@party.errors.count, "error") %> prohibited this party from being saved:</h2>

      <ul>
      <% @party.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :betfaircode %><br>
    <%= f.text_field :betfaircode %>
  </div>
  <div class="field">
    <%= f.label :odds %><br>
    <%= f.text_field :odds %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/parties/edit.html.erb
<h1>Editing Party</h1>

<%= render 'form' %>

<%= link_to 'Show', @party %> |
<%= link_to 'Back', parties_path %>

app/views/parties/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Parties</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Betfaircode</th>
      <th>Odds</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @parties.each do |party| %>
      <tr>
        <td><%= party.name %></td>
        <td><%= party.betfaircode %></td>
        <td><%= party.odds %></td>
        <td><%= link_to 'Show', party %></td>
        <td><%= link_to 'Edit', edit_party_path(party) %></td>
        <td><%= link_to 'Destroy', party, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Party', new_party_path %>

app/views/parties/new.html.erb
<h1>New Party</h1>

<%= render 'form' %>

<%= link_to 'Back', parties_path %>

app/views/parties/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @party.name %>
</p>

<p>
  <strong>Betfaircode:</strong>
  <%= @party.betfaircode %>
</p>

<p>
  <strong>Odds:</strong>
  <%= @party.odds %>
</p>

<%= link_to 'Edit', edit_party_path(@party) %> |
<%= link_to 'Back', parties_path %>

app/views/welcome/index.html.erb
  <!--<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/2.1.1/css/bootstrap.min.css">-->


<div class="container">
	<h1> Election Tipping </h1>

	<div class="page">

		
	</div>
	
	<div class="chart"></div>
	<div class="test"></div>

	<br>
	<br>


<div id="biocontent" style="display:none">
	<div class="bio info">
	<h2>Click on a candidate for more info</h2>
	</div>
	<div class="bio clinton">
	    <img src="http://www.abac.edu/wp-content/uploads/2013/01/democrat-logo.png" img class="logo">
	        <h2>Hillary Clinton</h2> 
	            <a href="https://www.hillaryclinton.com/"><img src="http://i.imgur.com/VVus0at.jpg?1"></a>
	         <a href="https://en.wikipedia.org/wiki/Hillary_Clinton">Wikipedia Page</a> 
	</div>

	<div class="bio sanders">
	    <img src="http://www.abac.edu/wp-content/uploads/2013/01/democrat-logo.png" img class="logo"> 
	        <h2>Bernie Sanders</h2>
	            <a href="https://secure.berniesanders.com/"><img src="http://i.imgur.com/gNamezs.jpg?1"></a>    
	        <a href="https://en.wikipedia.org/wiki/Bernie_Sanders">Wikipedia Page</a> <br>
	</div>


	<div class="bio rubio">
	    <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/Republicanlogo.svg/2000px-Republicanlogo.svg.png" img class="logo">
	        <h2>Marco Rubio</h2>
	             <a href=""https://marcorubio.com/""><img src="http://i.imgur.com/aK8zEgb.jpg?1"></a>
	        <a href="https://en.wikipedia.org/wiki/Marco_Rubio">Wikipedia Page</a> <br>
	</div>


	<div class="bio trump">
	    <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/Republicanlogo.svg/2000px-Republicanlogo.svg.png" img class="logo">
	        <h2>Donald Trump</h2>
	            <a href="https://www.donaldjtrump.com/"><img src="http://i.imgur.com/dfE8qHK.jpg?1"></a>    
	        <a href="https://en.wikipedia.org/wiki/Donald_Trump">Wikipedia Page</a> <br>
	</div>


	<div class="bio bush">
	    <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/Republicanlogo.svg/2000px-Republicanlogo.svg.png" img class="logo">
	        <h2>Jeb Bush</h2>
	            <a href="https://jeb2016.com/?lang=en"><img src="https://qph.is.quoracdn.net/main-thumb-t-33103-200-byvvznwiyapvmefbdliexfitsxdvjpqf.jpeg"></a>
	        <a href="https://en.wikipedia.org/wiki/Jeb_Bush">Wikipedia Page</a> <br>
	</div>

	<div class="bio carson">
	    <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/Republicanlogo.svg/2000px-Republicanlogo.svg.png" img class="logo"> 
	        <h2>Ben Carson</h2>
	            <a href="https://www.bencarson.com/"><img src="http://dehayf5mhw1h7.cloudfront.net/wp-content/uploads/sites/68/2015/11/06064014/ben-carson-oct-2015-billboard-650-200x200.jpg"></a>
	        <a href="https://en.wikipedia.org/wiki/Ben_Carson">Wikipedia Page</a> <br>
	</div>


	<div class="bio christie">
	    <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/Republicanlogo.svg/2000px-Republicanlogo.svg.png" img class="logo"> 
	        <h2>Chris Christie</h2>
	            <a href="https://www.chrischristie.com/"><img src="http://rs122.pbsrc.com/albums/o244/race42008/ChrisChristieR412.jpg~c200"></a>    
	        <a href="https://en.wikipedia.org/wiki/Chris_Christie">Wikipedia Page</a> <br>
	</div>

	<div class="bio cruz">
	    <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/Republicanlogo.svg/2000px-Republicanlogo.svg.png" img class="logo"> 
	        <h2>Ted Cruz</h2>
	            <a href="https://www.tedcruz.org/"><img src="http://dailysignal.com/wp-content/uploads/Cruz-Headshot-2-200x200.jpg"></a>    
	        <a href="https://en.wikipedia.org/wiki/Ted_Cruz">Wikipedia Page</a> <br>
	</div>
</div>